name: tda_sleep_staging_env
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=3.11.0
  - jupyterlab=4.2.3
  - mne=1.7.1
  - numpy=1.26.4
  - pandas=2.2.2
  - pip==24.0
  - python=3.12.4
  - scipy=1.14.0
  - tqdm=4.66.4
  - pip:
    - click==8.1.7
    - cripser==0.0.13
    - cython==3.0.10
    - data==0.4
    - docker-pycreds==0.4.0
    - dtw-python==1.5.1
    - fire==0.6.0
    - funcsigs==1.0.2
    - giotto-ph==0.2.4
    - giotto-tda==0.6.2
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gudhi==3.10.1
    - hermite-function==2.0
    - hopcroftkarp==1.2.5
    - igraph==0.11.6
    - latex==0.7.0
    - mpmath==1.3.0
    - neurokit2==0.2.9
    - persim==0.3.5
    - plotly==5.22.0
    - pot==0.9.4
    - protobuf==5.27.2
    - pyaml==24.7.0
    - pyentrp==1.0.0
    - pyflagser==0.4.7
    - pyparsing==3.0.9
    - ripser==0.6.8
    - scikit-learn==1.3.2
    - sentry-sdk==2.11.0
    - setproctitle==1.3.3
    - shutilwhich==1.1.0
    - smmap==5.0.1
    - sortedcontainers==2.4.0
    - sympy==1.13.1
    - tempdir==0.7.1
    - tenacity==8.5.0
    - termcolor==2.4.0
    - texttable==1.7.0
    - vector==1.4
    - wandb==0.17.5
    - xgboost==2.1.0
